### ISSUE TITLE
Set stage to run new analysis

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#20]
The following points come to mind:
- Remove files from previous run (dealt with partly now). What about deleting everything in the OUT folder? Then we won't run into problems of e.g. csv-files leading to errors in PeptideShaker (see also #19)
- Create button to reset all scripts (or specifically delete files and rerun the cell with the widgets)

**Comment by jgriss** [comment]
If we delete everything in "OUT" I users could unintentionally delete files they don't want to delete. Alternatively, if the output directory is not empty when the search is launched we could simply create a new directory called "OUT.2", for example.

**Comment by veitveit** [comment]
Moving the old files to a different folder might be better
