### ISSUE TITLE
Add auto methods section function

### ISSUE THREAD

**Issue by jgriss** [ProtProtocols/IsoLabeledProtocol#23]
Add a function to automatically generate a methods section that can be copied into a manuscript.

**Comment by veitveit** [comment]
PeptideShaker provides a text with the methods, you might want to use this as template

**Comment by jgriss** [comment]
@veitveit 
Please have a look at it. It's not a perfect text but a starting point users can adapt.

**Comment by jgriss** [comment]
Basic functionality is there.
