### ISSUE TITLE
Add warning if multiple MGF files are found

### ISSUE THREAD

**Issue by jgriss** [ProtProtocols/IsoLabeledProtocol#27]
In case that multiple MGF files are present in the input directory, the user should be prompted about how these are handled.

In the current workflow, these should be treated as different fractions of the same sample.

In future workflows, the user could be prompted to choose what these files represent.

**Comment by veitveit** [comment]
Do we still need that? It is very common to have multiple files for the same run. If we make clear that different MS runs need to be arranged in different folders, then we don't need to have a warning here

**Comment by jgriss** [comment]
This is now obsolete due to #4
