### ISSUE TITLE
Reorder widgets and disable in the right order

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#34]
Parameters for protein quantification (e.g. summarization method) should come after the experimental design. The user should be able to update them so they can try and compare different methods. 

So the order would be
a) database search
b) experimental design
c) quantification

It is OK when database search parameters and experimental design cannot be changed anymore after running the search. Additionally, the quantification parameters should be updated accordingly in the parameters file/instance when pressing the "run R scripts" button. This does not happen so far.

**Comment by jgriss** [comment]
@veitveit 

While adapting our GUI elements I thought whether it might be better to change the workflow a bit:

1) Show file & search related elements
2) Show the "run search" button
3) Once the search is complete, show the design UI + the R settings elements together with the "Run R analysis" button

That way, the user automatically sees that the search elements are linked to the search, and that if these parameters are changed, that the search has to be repeated.

Additionally, the parameters that only influence the R analysis are more separated from the others and it's more clear that the R analysis can be repeated without repeating the search.

**Comment by jgriss** [comment]
I'm now going to simply try this. I'll move these changes to a different branch so we can easily revert.

**Comment by veitveit** [comment]
@jgriss  
I don't think this is a very good idea as all parameters should preferable be set before running the search, or optionally the entire analysis (as we called it a one-stop shop). Why don't we change the buttons to "run everything" and then add a button to "rerun quantitative analysis" and one for re-run from the start? Two components take most of the time: database search and mapping identification to spectra to extract the reporter ions. Everything after that is quite fast and could deserve a separate button, so the user can play with the options.
