### ISSUE TITLE
Update configuration settings when changing the parameters

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#36]
This goes together with #34. For instance, changes of the quantification method should update the parameter object, so one can rerun the scripts without having to run from the start.

**Comment by jgriss** [comment]
@veitveit 

I am not quite sure that I understand this correctly: Do you mean that if the user changes the quant method drop-down, that the R object storing the settings should be changed? That's unfortunately not possible. Also, the experimental design needs to be adapted if the quant method is changed.

So I'm not quite sure I fully understand what you mean.

**Comment by veitveit** [comment]
@jgriss  I meant the "summarization method", sorry. 

Let's say one wants to run the R scripts changes parameters for essentially everything under the "Quantification" section of the parameters but "number of experimental conditions", e.g. to try different summarization methods or different minimum numbers of PSMs, the parameter object could be updated. 

Actually, also the experimental design should be easy to update given that the database search parameters, particularly the quantification methods (iTRAQ, TMT), are fixed.

The question is how easy an observer can be implemented, that monitors these parameters.

**Comment by jgriss** [comment]
@veitveit 

Now I understand! Updating everything when the user clicks the button can be done. Everything else would be quite tricky. Do you think that's enough?

If yes, I'll start working on that.

**Comment by veitveit** [comment]
@jgriss  Can you do that soon? I tested the protocol with different data sets and this is holding me back. See also #48
