### ISSUE TITLE
veitveit/isolabeledprotocol or label_pipeline

### ISSUE THREAD

**Issue by gvinterhalter** [ProtProtocols/IsoLabeledProtocol#39]
`rebuild_docker.sh` is building `label_pipeline`, but I would assume that is wrong?

Can someone check to make sure there is only one name (in all files)?

**Comment by veitveit** [comment]
I we want to distinguish local and global versions of the image, then there should be to names. The official name is veitveit/isolabeledprotocol and is automatically generated at the docker cloud when uploading something to github. As this takes about 45 min, a local version for testing might be useful.

**Comment by jgriss** [comment]
As `label_pipeline` is only referenced in the local rebuild script I don't think that this will cause any problems. In my opinion, this is actually quite elegant to prevent any confusion.
