### ISSUE TITLE
Save parameters in json file and load them in R again

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#48]
This becomes more and more important when testing the protocol. Save the json file in the OUT folder so it always can be found.

By having all parameters saved instead of having them only defined as variable crucially helps when wanting to continue the analysis after the database search, especially when the notebook has been closed.

**Comment by veitveit** [comment]
This is related to #36 and #47

**Comment by veitveit** [comment]
The parameters are now saved when pressing the "Database search" button. 

BUT: I did not manage to write the file into the _OUT_ folder, so this needs correction. 

We also need to have the output from the database search written into json

**Comment by jgriss** [comment]
As far as I understand, this issue describes the following steps:

1. Save configuration (this currently doesn't work)
2. Load configuration if the output already exists to be able to resume a project / analysis
