### ISSUE TITLE
Save (search) output to log file

### ISSUE THREAD

**Issue by jgriss** [ProtProtocols/IsoLabeledProtocol#58]
Currently, when a running notebook is closed (in my case the search) the notebook is still executed, but the output is lost - and cannot be retrieved afterwards according to several bug reports.

A possible solution to this is to use a proper logging system in the search.ipy module and write every message to the notebook (using `print`) as well as to a log file.

Ideally, when the notebook is re-opened, we could display the contents of the log file.

**Comment by veitveit** [comment]
@jgriss Is it possible to write all SearchGUI and PeptideShaker output into a log-file? I cannot find this information anywhere which makes it very tricky to identify the error when something is going wrong.

Maybe just capture all output to stdout and stderr from the python script?

**Comment by jgriss** [comment]
@veitveit I'll start working on that

**Comment by veitveit** [comment]
@jgriss Can that be moved to the _LOG_ folder?

**Comment by jgriss** [comment]
@veitveit I've now put the location of the log file to "OUT/LOG"

Is that OK?

**Comment by veitveit** [comment]
Yes, and better :+1:
