### ISSUE TITLE
Clean source code

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#61]
Remove obsolete files

**Comment by jgriss** [comment]
@veitveit 
How about renaming `Example.ibnyp` to `TMT Workflow.ibnyp`?

In the future, we might have additional notebooks, ie for phospho site analysis. Then, Exambple.ibnyp might not be the best name for it.

**Comment by veitveit** [comment]
Agreed

**Comment by jgriss** [comment]
@veitveit 

Files I think can be removed:

  * OrgPipeline
  * .RHistory (should probably be added to .gitignore)
  * Eubic_logo.png -> to misc
  * Example_msnbase.ipynb

**Comment by veitveit** [comment]
Let's remove these files after the workshop to be on the safe side.
 
* pipeline.sh

The workflow could also be named "Isobaric Workflow.ipynb" so the missing "iTRAQ" does not confuse.
