### ISSUE TITLE
Define docker release process

### ISSUE THREAD

**Issue by jgriss** [ProtProtocols/IsoLabeledProtocol#63]
I know we had this issue before, but I feel that we still net to clarify the release process a bit:

  1.) Define files that are shipped to the user (as a zip file). This is done by adding the run.sh / run.bat files
  2.) Adapt all files that contain version numbers - ie. that need to be updated
    * Adapt the README.md file to point to that version as the latest stable version (ie. update the shown `docker pull` command).
    * Adapt the run.sh / run.cmd file to install the version by default
    * Adapt the methods_generator module to print the correct version.
  3.) Once we have completed a version, a docker image with that version number needs to be build. We need to check how that can be done.

The exact step of how to prepare a release should be put in a `HowTo_Release.md` file.

Let's add thoughts under this issue and once we have everything, let's create the file.

**Comment by veitveit** [comment]
@jgriss 

1) Is there anything more than the run.sh/bat files?
2) These will have to be done manually, I assume
3) should be working automatically when assigning a release via github.

**Comment by veitveit** [comment]
@jgriss 
As time is running, I will make the current version a release assuming that we still will be able to revise if necessary.

**Comment by veitveit** [comment]
Any release with a numbering code is automatically creating a dedicated docker image, see https://cloud.docker.com/swarm/veitveit/repository/docker/veitveit/isolabeledprotocol/general

So no work required :-)
