### ISSUE TITLE
wrong estimation of free memory

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#64]
The _free_mem_ option underestimates the available memory.

E.g. we had 8 GB and it assigned about 2GB or less. 

Could be a Docker issue.

**Comment by veitveit** [comment]
In the docker toolbox, maybe the default memory of the VirtualBox is too low?

**Comment by jgriss** [comment]
Hi @veitveit 
I now double checked: On windows (windows 10 with "native" docker and docker toolbox as well) docker is run in a virtual (linux) machine. Therefore, the memory settings of that machine are what we see in our docker setting.

I will double check how these settings can be adapted in the toolbox setup

**Comment by veitveit** [comment]
@jgriss This page might be useful:
https://blog.pavelsklenar.com/5-useful-docker-tip-and-tricks-on-windows/
