### ISSUE TITLE
Releases should contain ready prepared zip files to download

### ISSUE THREAD

**Issue by jgriss** [ProtProtocols/IsoLabeledProtocol#68]
At the moment, the release only contains a zip file with the complete source code.

It would be nicer if we had one zip file for windows and linux (or even only the run.sh for linux) so users immediately know what to download.

**Comment by veitveit** [comment]
@jgriss This might become obsolete with the launcher as the zip files then will be to provide the source code

**Comment by jgriss** [comment]
@veitveit Yes! The launcher will automatically detect if a new version is available. Therefore, we'll only have to release a new docker version and not worry about the rest.
