### ISSUE TITLE
Loading previous data triggers error in R scripts

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#70]
Some configuration was not read correctely:

"Error in qnt[[i]] : subscript out of bounds"

**Comment by veitveit** [comment]
@jgriss 

I might need your help here. This happens because the "mgf.filtered" files are not anymore there when reopening the Docker image.

It might help to copy all manipulated versions of the mgf input files to the _OUT_ folder. Is that feasible?

**Comment by jgriss** [comment]
@veitveit The .fitlered MGF files are now written to the `OUT` directory. Respective R code in the notebook is updated. Please test if it works for your cases.

**Comment by veitveit** [comment]
Seems to work, great!
