### ISSUE TITLE
Ensure that Notebooks do not contain any cell output

### ISSUE THREAD

**Issue by jgriss** [ProtProtocols/IsoLabeledProtocol#72]
If a Notebook is saved with cell output present (ie. a button) the IPython kernel is launched to interpret this output whenever the user opens the notebook. This is independent of the "initialized cells".

If this happens, the launch of the IPython kernel (to interpret the output) interferes with the cell initialization and some UI controls may not be displayed.

**TODO**: 
@veitveit Is there any method to clear all cell output when building the docker image?

Otherwise, we need to be very careful to only commit Notebook versions that do not contain any output.

**Comment by veitveit** [comment]
Line has been added to Dockerfile and seems to work now
